{
  "openapi": "3.0.1",
  "info": {
    "title": "Simulator.Company REST API",
    "description": "Simulator.Company Public REST API.\n\n# Authentication\n\n<!-- ReDoc-Inject: <security-definitions> -->",
    "x-logo": {
      "url": "https://sim.simulator.company/static/logo.svg",
      "padding": "24px",
      "altText": "Simulator.Company"
    },
    "contact": {
      "email": "support@simulator.company"
    },
    "version": "1.0"
  },
  "servers": [
    {
      "url": "https://mw-api.simulator.company/v/1.0"
    }
  ],
  "tags": [
    {
      "name": "reactions",
      "description": "Reactions API"
    },
    {
      "name": "upload",
      "description": "Upload API"
    },
    {
      "name": "download",
      "description": "Download API"
    },
    {
      "name": "attachments",
      "description": "Attachments API"
    },
    {
      "name": "forms",
      "description": "Forms API"
    },
    {
      "name": "meta graph",
      "description": "Meta graph API"
    },
    {
      "name": "layers",
      "description": "Layers API"
    },
    {
      "name": "actors",
      "description": "Actors API"
    },
    {
      "name": "links",
      "description": "Actors links API"
    },
    {
      "name": "link types",
      "description": "Link types API"
    },
    {
      "name": "accounts",
      "description": "Actors accounts API"
    },
    {
      "name": "transactions",
      "description": "Transactions API"
    },
    {
      "name": "transfers",
      "description": "Transfers API"
    },
    {
      "name": "account names",
      "description": "Accounts names API"
    },
    {
      "name": "currencies",
      "description": "Accounts currencies API"
    },
    {
      "name": "access rules",
      "description": "Access rules API"
    },
    {
      "name": "users",
      "description": "Users API"
    },
    {
      "name": "realtime",
      "description": "Realtime API"
    }
  ],
  "paths": {
    "/reactions/{type}/{actorId}": {
      "post": {
        "tags": [
          "reactions"
        ],
        "summary": "Create reaction",
        "description": "Scopes [control.events:actors.management]",
        "operationId": "createReaction",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/reactions/list/{actorId}": {
      "get": {
        "tags": [
          "reactions"
        ],
        "summary": "Get all actor reactions",
        "description": "Scopes [control.events:actors.readonly]",
        "operationId": "getReactions",
        "security": [
          {
            "OAuth2": [
              "control.events:reactions.readonly"
            ]
          }
        ]
      }
    },
    "/reactions/stats/{actorId}": {
      "get": {
        "tags": [
          "reactions"
        ],
        "summary": "Get reactions statistics",
        "description": "Scopes [control.events:actors.readonly]",
        "operationId": "getActorReactionsStats",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.readonly"
            ]
          }
        ]
      }
    },
    "/reactions/{rootActorId}": {
      "put": {
        "tags": [
          "reactions"
        ],
        "summary": "Update reaction",
        "description": "Scopes [control.events:actors.management]",
        "operationId": "updateReaction",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/reactions/{actorId}": {
      "delete": {
        "tags": [
          "reactions"
        ],
        "summary": "Remove reaction",
        "description": "Scopes [control.events:actors.management]",
        "operationId": "removeReaction",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/reactions/read/{actorId}": {
      "post": {
        "tags": [
          "reactions"
        ],
        "summary": "Mark reactions as read",
        "description": "Scopes [control.events:actors.management]",
        "operationId": "readReactions",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/upload/{accId}": {
      "post": {
        "tags": [
          "upload"
        ],
        "summary": "Upload file",
        "description": "Scopes [control.events:attachments.management]",
        "operationId": "uploadFile",
        "security": [
          {
            "OAuth2": [
              "control.events:attachments.management"
            ]
          }
        ]
      }
    },
    "/upload/base64/{accId}": {
      "post": {
        "tags": [
          "upload"
        ],
        "summary": "Upload file base64",
        "description": "Scopes [control.events:attachments.management]",
        "operationId": "uploadFileBase64",
        "security": [
          {
            "OAuth2": [
              "control.events:attachments.management"
            ]
          }
        ]
      }
    },
    "/download/{fileName}": {
      "get": {
        "tags": [
          "download"
        ],
        "summary": "Download file",
        "operationId": "download"
      }
    },
    "/download/zip/{accId}": {
      "post": {
        "tags": [
          "download"
        ],
        "summary": "Download zipped files",
        "description": "Scopes [control.events:attachments.management]",
        "operationId": "downloadZip",
        "security": [
          {
            "OAuth2": [
              "control.events:attachments.management"
            ]
          }
        ]
      }
    },
    "/attachments/{accId}": {
      "get": {
        "tags": [
          "attachments"
        ],
        "summary": "Get all attachments",
        "description": "Scopes [control.events:attachments.readonly]",
        "operationId": "getAttachments",
        "security": [
          {
            "OAuth2": [
              "control.events:attachments.readonly"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "attachments"
        ],
        "summary": "Add attachment to actor",
        "description": "Scopes [control.events:attachments.management]",
        "operationId": "addAttachment",
        "security": [
          {
            "OAuth2": [
              "control.events:attachments.management"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "attachments"
        ],
        "summary": "Remove attachment",
        "description": "Scopes [control.events:attachments.management]",
        "operationId": "removeAttachment",
        "security": [
          {
            "OAuth2": [
              "control.events:attachments.management"
            ]
          }
        ]
      }
    },
    "/attachments/files": {
      "delete": {
        "tags": [
          "attachments"
        ],
        "summary": "Remove attachment files",
        "description": "Deleting files should not be attached to actors",
        "operationId": "removeAttachmentFile"
      }
    },
    "/counters/{accId}": {
      "post": {
        "tags": [
          "counters"
        ],
        "summary": "Create counters",
        "description": "Scopes [control.events:actors.readonly]",
        "operationId": "createCounters",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.readonly"
            ]
          }
        ]
      }
    },
    "/counters/list/{accId}": {
      "post": {
        "tags": [
          "counters"
        ],
        "summary": "Get list of counters",
        "description": "Scopes [control.events:actors.readonly]",
        "operationId": "getListOfCounters",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.readonly"
            ]
          }
        ]
      }
    },
    "/counters/uniq_values/{accId}": {
      "post": {
        "tags": [
          "counters"
        ],
        "summary": "Get uniq counter value",
        "description": "Scopes [control.events:actors.readonly]",
        "operationId": "getUniqCounterValue",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.readonly"
            ]
          }
        ]
      }
    },
    "/counters/list/uniq_values/{accId}": {
      "post": {
        "tags": [
          "counters"
        ],
        "summary": "Get list of uniq counter values",
        "description": "Scopes [control.events:actors.readonly]",
        "operationId": "getListOfUniqCounterValues",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.readonly"
            ]
          }
        ]
      }
    },
    "/forms/templates/{accId}": {
      "get": {
        "tags": [
          "forms"
        ],
        "summary": "Get list of forms",
        "description": "Scopes [control.events:forms.readonly]",
        "operationId": "getForms",
        "security": [
          {
            "OAuth2": [
              "control.events:forms.readonly"
            ]
          }
        ]
      }
    },
    "/forms/templates/system/{accId}?formTypes=system": {
      "get": {
        "tags": [
          "forms"
        ],
        "summary": "Get list of system forms",
        "description": "This API is used to get system forms:\n* Graphs\n* Layers\n* Streams\n* Events\n* Widgets\n* Scripts\n* Locations\n* Tags\n* Reactions\n\nScopes [control.events:forms.readonly]\n",
        "operationId": "getSystemForms",
        "security": [
          {
            "OAuth2": [
              "control.events:forms.readonly"
            ]
          }
        ]
      }
    },
    "/forms/{accId}/{isTemplate}": {
      "post": {
        "tags": [
          "forms"
        ],
        "summary": "Create form",
        "description": "Scopes [control.events:forms.management]",
        "operationId": "createForm",
        "security": [
          {
            "OAuth2": [
              "control.events:forms.management"
            ]
          }
        ]
      }
    },
    "/forms/status/{formId}": {
      "put": {
        "tags": [
          "forms"
        ],
        "summary": "Set form status",
        "description": "Scopes [control.events:forms.management]",
        "operationId": "setFormStatus",
        "security": [
          {
            "OAuth2": [
              "control.events:forms.management"
            ]
          }
        ]
      }
    },
    "/forms/ref/{ref}": {
      "get": {
        "tags": [
          "forms"
        ],
        "summary": "Get form by ref",
        "description": "Scopes [control.events:forms.readonly]",
        "operationId": "getFormByRef",
        "security": [
          {
            "OAuth2": [
              "control.events:forms.readonly"
            ]
          }
        ]
      }
    },
    "/forms/{formId}": {
      "get": {
        "tags": [
          "forms"
        ],
        "summary": "Get form by ID",
        "description": "Scopes [control.events:forms.readonly]",
        "operationId": "getForm",
        "security": [
          {
            "OAuth2": [
              "control.events:forms.readonly"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "forms"
        ],
        "summary": "Update form",
        "description": "Scopes [control.events:forms.management]",
        "operationId": "updateForm",
        "security": [
          {
            "OAuth2": [
              "control.events:forms.management"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "forms"
        ],
        "summary": "Remove form",
        "description": "Scopes [control.events:forms.management]",
        "operationId": "deleteForm",
        "security": [
          {
            "OAuth2": [
              "control.events:forms.management"
            ]
          }
        ]
      }
    },
    "/form_accounts/{formId}": {
      "post": {
        "tags": [
          "forms"
        ],
        "summary": "Add account-currency pair to form",
        "description": "Adds an account-currency pair to the specified form. Scopes [control.events:forms.management]",
        "operationId": "addFormAccount",
        "security": [
          {
            "OAuth2": [
              "control.events:forms.management"
            ]
          }
        ]
      }
    },
    "/forms/item_cache/{formId}/{itemId}": {
      "delete": {
        "tags": [
          "forms"
        ],
        "summary": "Clear cache for form item options",
        "description": "Helps to clear cache for form item options, where source type is 'api'.<br/><br/> Scopes [control.events:forms.management]",
        "operationId": "clearFromItemSourceCache",
        "security": [
          {
            "OAuth2": [
              "control.events:forms.management"
            ]
          }
        ]
      }
    },
    "/graph/linked_actors/{actorId}": {
      "get": {
        "tags": [
          "meta graph"
        ],
        "summary": "Get linked actors with links",
        "description": "Scopes [control.events:actors.readonly]",
        "operationId": "getLinkedActors",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.readonly"
            ]
          }
        ]
      }
    },
    "/graph/actor_links/{actorId}": {
      "get": {
        "tags": [
          "meta graph"
        ],
        "summary": "Get all actor links",
        "description": "Scopes [control.events:actors.readonly]",
        "operationId": "getActorLinks",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.readonly"
            ]
          }
        ]
      }
    },
    "/actors/exist_link": {
      "post": {
        "tags": [
          "meta graph"
        ],
        "summary": "Check if link exists",
        "description": "Scopes [control.events:actors.readonly]",
        "operationId": "existLink",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.readonly"
            ]
          }
        ]
      }
    },
    "/graph/{type}/{actorId}": {
      "get": {
        "tags": [
          "meta graph"
        ],
        "summary": "Get linked actors",
        "description": "Scopes [control.events:actors.readonly]",
        "operationId": "getLinked",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.readonly"
            ]
          }
        ]
      }
    },
    "/graph_layers/{layerId}": {
      "get": {
        "tags": [
          "layers"
        ],
        "summary": "Get layer",
        "description": "Scopes [control.events:actors.readonly]\n\nA layer is an actor created with system form [Layers](api.html#operation/getSystemForms).\nThis API retrieves all layer actor data together with it's nodes and links.\n",
        "operationId": "getLayer",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.readonly"
            ]
          }
        ]
      }
    },
    "/graph_layers/actors/{layerId}": {
      "post": {
        "tags": [
          "layers"
        ],
        "summary": "Manage layer elements",
        "description": "Scopes [control.events:actors.management]",
        "operationId": "manageLayer",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "layers"
        ],
        "summary": "Save layer nodes positions on layer",
        "description": "Scopes [control.events:actors.management]",
        "operationId": "layerActorsPosition",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/graph_layers/move/{sourceLayerId}/{targetLayerId}": {
      "post": {
        "tags": [
          "layers"
        ],
        "summary": "Move actors to another layer",
        "description": "Scopes [control.events:actors.management]",
        "operationId": "moveElements",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/graph_layers/clean/{layerId}": {
      "delete": {
        "tags": [
          "layers"
        ],
        "summary": "Clear the layer",
        "description": "Scopes [control.events:actors.management]",
        "operationId": "cleanLayer",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/graph_layers/exist/{layerId}": {
      "post": {
        "tags": [
          "layers"
        ],
        "summary": "Check element existence",
        "description": "Scopes [control.events:actors.readonly]\n\nThis method searches an element on the layer and returns a list of their layer-unique IDs.\n",
        "operationId": "exist",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/layer_actors_filters/search/{layerId}/{query}": {
      "get": {
        "tags": [
          "layers"
        ],
        "summary": "Search layer actors",
        "description": "Scopes [control.events:actors.readonly]",
        "operationId": "searchLayerActors",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/layer_actors_filters/{layerId}/{formId}": {
      "get": {
        "tags": [
          "layers"
        ],
        "summary": "Get layer actors by form ID",
        "description": "Scopes [control.events:actors.readonly]\n\nThis method returns all layer actors filtered by form ID.\n",
        "operationId": "getLayerActorsByFormId",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/layers_links/actor_global/{actorId}": {
      "get": {
        "tags": [
          "layers"
        ],
        "summary": "Get all graph layers with actor",
        "description": "Scopes [control.events:actors.readonly]\n\nThis method retrieves all layers where the actor is added.\n",
        "operationId": "actorGlobalLayers",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/actors/actor/{formId}": {
      "post": {
        "tags": [
          "actors"
        ],
        "summary": "Create actor",
        "description": "Scopes [control.events:actors.management]",
        "operationId": "createActor",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/actors/{actorId}": {
      "get": {
        "tags": [
          "actors"
        ],
        "summary": "Get actor by ID",
        "description": "Scopes [control.events:actors.readonly]",
        "operationId": "getActor",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.readonly"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "actors"
        ],
        "summary": "Remove actor by ID",
        "description": "Scopes [control.events:actors.management]",
        "operationId": "deleteActor",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/actors": {
      "delete": {
        "tags": [
          "actors"
        ],
        "summary": "Remove multiple actors and links",
        "description": "Scopes [control.events:actors.management]",
        "operationId": "deleteBulk",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/actors/actor/{formId}/{actorId}": {
      "put": {
        "tags": [
          "actors"
        ],
        "summary": "Update actor by ID",
        "description": "Scopes [control.events:actors.management]",
        "operationId": "updateActor",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/actors/ref/{formId}/{ref}": {
      "get": {
        "tags": [
          "actors"
        ],
        "summary": "Get actor by ref",
        "description": "Scopes [control.events:actors.readonly]",
        "operationId": "getActorByRef",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.readonly"
            ]
          }
        ]
      }
    },
    "/actors/system/{accId}/{objType}/{objId}": {
      "get": {
        "tags": [
          "actors"
        ],
        "summary": "Get actor by systemObjId",
        "description": "Scopes [control.events:actors.readonly]",
        "operationId": "getActorByObjId",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.readonly"
            ]
          }
        ]
      }
    },
    "/actors/ref/{{formId}}/{{ref}}": {
      "delete": {
        "tags": [
          "actors"
        ],
        "summary": "Remove actor by ref",
        "description": "Scopes [control.events:actors.management]",
        "operationId": "deleteActorByRef",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/actors/actor/ref/{formId}/{ref}": {
      "put": {
        "tags": [
          "actors"
        ],
        "summary": "Update actor by ref",
        "description": "Scopes [control.events:actors.management]",
        "operationId": "updateActorByRef",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/actors/status/{actorId}": {
      "put": {
        "tags": [
          "actors"
        ],
        "summary": "Set actor status",
        "description": "Scopes [control.events:actors.management]",
        "operationId": "setActorStatus",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/actors_filters/search/{accId}/{query}": {
      "get": {
        "tags": [
          "actors"
        ],
        "summary": "Search actors",
        "description": "Scopes [control.events:actors.readonly]",
        "operationId": "searchActors",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.readonly"
            ]
          }
        ]
      }
    },
    "/actors_filters/{formId}": {
      "get": {
        "tags": [
          "actors"
        ],
        "summary": "Filter actors by form",
        "description": "Scopes [control.events:actors.readonly]. Samples of params: Get only one actor and specify fields to return: \n  {\"from\": 0, \"to\": 1755540313, \"limit\":1, \"filter\":\"id,title\"} \n Get first 10 actors with all fields: \n  {\"from\": 0, \"to\": 1755540313, \"limit\":10}",
        "operationId": "filterActors",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.readonly"
            ]
          }
        ]
      }
    },
    "/actors/link/{accId}": {
      "post": {
        "tags": [
          "links"
        ],
        "summary": "Create link between actors",
        "description": "Scopes [control.events:actors.management]",
        "operationId": "createLink",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/actors/mass_links/{accId}": {
      "post": {
        "tags": [
          "links"
        ],
        "summary": "Create multiple links",
        "description": "Scopes [control.events:actors.management]",
        "operationId": "massLink",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/actors/link/{edgeId}": {
      "put": {
        "tags": [
          "links"
        ],
        "summary": "Update link",
        "description": "Scopes [control.events:actors.management]",
        "operationId": "updateLink",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "links"
        ],
        "summary": "Remove link",
        "description": "Scopes [control.events:actors.management]",
        "operationId": "deleteLink",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/actors/bulk/actors_link": {
      "delete": {
        "tags": [
          "links"
        ],
        "summary": "Mass remove links",
        "description": "Scopes [control.events:actors.management]",
        "operationId": "bulkDeleteLinks",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/accounts/{actorId}": {
      "get": {
        "tags": [
          "accounts"
        ],
        "summary": "Get list of accounts by actor ID",
        "description": "Scopes [control.events:actors.readonly]",
        "operationId": "getAccounts",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.readonly"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "accounts"
        ],
        "summary": "Create accounts by actor ID",
        "description": "Scopes [control.events:actors.management]",
        "operationId": "createAccounts",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/accounts/{actorId}/{currencyId}/{nameId}": {
      "get": {
        "tags": [
          "accounts"
        ],
        "summary": "Get actor's accounts by currency ID and name ID",
        "description": "Scopes [control.events:actors.readonly]",
        "operationId": "getAccountsByCurAccName",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.readonly"
            ]
          }
        ]
      }
    },
    "/accounts/children/{actorId}": {
      "get": {
        "tags": [
          "accounts"
        ],
        "summary": "Get children accounts by actor ID",
        "description": "Scopes [control.events:actors.readonly]",
        "operationId": "getChildrenAccounts",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.readonly"
            ]
          }
        ]
      }
    },
    "/accounts/{actorId}/{currencyId}/{nameId}/{accountType}": {
      "delete": {
        "tags": [
          "accounts"
        ],
        "summary": "Remove accounts by actor ID",
        "description": "Scopes [control.events:actors.management]",
        "operationId": "delAccounts",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/accounts/block/{actorId}": {
      "put": {
        "tags": [
          "accounts"
        ],
        "summary": "Block account by actor ID",
        "description": "Scopes [control.events:actors.management]",
        "operationId": "blockAccount",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.readonly"
            ]
          }
        ]
      }
    },
    "/accounts/single/ref/{formId}/{ref}": {
      "get": {
        "tags": [
          "accounts"
        ],
        "summary": "Get single account by actor ref",
        "description": "Scopes [control.events:actors.readonly]",
        "operationId": "getSingleAccountByActorRef",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.readonly"
            ]
          }
        ]
      }
    },
    "/accounts/ref/{formId}/{ref}": {
      "get": {
        "tags": [
          "accounts"
        ],
        "summary": "Get list of accounts by actor ref",
        "description": "Scopes [control.events:actors.readonly]",
        "operationId": "getAccountsByActorRef",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.readonly"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "accounts"
        ],
        "summary": "Create accounts by actor ref",
        "description": "Scopes [control.events:actors.management]",
        "operationId": "createAccountsByRef",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/accounts/pair/{accId}": {
      "post": {
        "tags": [
          "accounts"
        ],
        "summary": "Create account pair",
        "description": "Gives opportunity to create account pair with name and currency.",
        "operationId": "postAccounts",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/accounts/children/ref/{formId}/{ref}": {
      "get": {
        "tags": [
          "accounts"
        ],
        "summary": "Get children accounts by actor ref",
        "description": "Scopes [control.events:actors.readonly]",
        "operationId": "getChildrenAccountsByActorRef",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.readonly"
            ]
          }
        ]
      }
    },
    "/accounts/ref/{formId}/{ref}/{currencyId}/{nameId}/{accountType}": {
      "delete": {
        "tags": [
          "accounts"
        ],
        "summary": "Remove accounts by actor ref",
        "description": "Scopes [control.events:actors.management]",
        "operationId": "delAccountsByActorRef",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/accounts/single/{accountId}": {
      "get": {
        "tags": [
          "accounts"
        ],
        "summary": "Get account by ID",
        "description": "Scopes [control.events:actors.readonly]",
        "operationId": "getAccount",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.readonly"
            ]
          }
        ]
      }
    },
    "/accounts/bulk": {
      "get": {
        "tags": [
          "accounts"
        ],
        "summary": "Get accounts by array of IDs",
        "description": "Scopes [control.events:actors.readonly]",
        "operationId": "getAccountBulk",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.readonly"
            ]
          }
        ]
      }
    },
    "/accounts/bulk/actors_refs/{nameId}/{currencyId}": {
      "post": {
        "tags": [
          "accounts"
        ],
        "summary": "Get accounts by array of actors refs",
        "description": "Scopes [control.events:actors.readonly]",
        "operationId": "getAccountBulkRefs",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.readonly"
            ]
          }
        ]
      }
    },
    "/accounts/amount/{accountId}": {
      "put": {
        "tags": [
          "accounts"
        ],
        "summary": "Set account amount",
        "description": "Scopes [control.events:actors.management]",
        "operationId": "setAmount",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/accounts/formula/{accountId}": {
      "post": {
        "tags": [
          "accounts"
        ],
        "summary": "Set account formula",
        "description": "'Scopes [control.events:actors.management]'\n\n**Supported functions syntax**<br/>\n`sum(a, b, c, ...)` - returns the sum of all the arguments passed<br/>\n`mean(a, b, c, ...)` - returns a numeric value that is the arithmetic mean (average) of its arguments<br/>\nUse account ID as an argument to calculate it's amount with formula.\n",
        "operationId": "setFormula",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.readonly"
            ]
          }
        ]
      }
    },
    "/accounts/formula_info/{accountId}": {
      "get": {
        "tags": [
          "accounts"
        ],
        "summary": "Get account formula info",
        "description": "Scopes [control.events:actors.readonly]",
        "operationId": "getFormulaInfo",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.readonly"
            ]
          }
        ]
      }
    },
    "/transactions/{actorId}": {
      "get": {
        "tags": [
          "transactions"
        ],
        "summary": "Get list of transactions by actor ID",
        "description": "Scopes [control.events:actors.readonly]",
        "operationId": "getTransactionsByActorID",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.readonly"
            ]
          }
        ]
      }
    },
    "/transactions/actor_ref/{formId}/{actorRef}": {
      "get": {
        "tags": [
          "transactions"
        ],
        "summary": "Get list of transactions by actor ref",
        "description": "Scopes [control.events:actors.readonly]",
        "operationId": "getTransactionsByActorRef",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.readonly"
            ]
          }
        ]
      }
    },
    "/transactions/list/{accountId}": {
      "get": {
        "tags": [
          "transactions"
        ],
        "summary": "Get list of transactions by account id",
        "description": "Scopes [control.events:actors.readonly]",
        "operationId": "getTransactionsByAccountId",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.readonly"
            ]
          }
        ]
      }
    },
    "/transactions/ref/{accountId}/{ref}": {
      "get": {
        "tags": [
          "transactions"
        ],
        "summary": "Get transaction by ref",
        "description": "Scopes [control.events:actors.readonly]",
        "operationId": "getTransactionByRef",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.readonly"
            ]
          }
        ]
      }
    },
    "/transactions/children/{transactionId}": {
      "get": {
        "tags": [
          "transactions"
        ],
        "summary": "Get child transactions",
        "description": "Scopes [control.events:actors.readonly]",
        "operationId": "getTransactionChildren",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.readonly"
            ]
          }
        ]
      }
    },
    "/transactions/{accountId}": {
      "post": {
        "tags": [
          "transactions"
        ],
        "summary": "Create transaction",
        "description": "Scopes [control.events:actors.management]",
        "operationId": "createTransaction",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/transactions/atom/{accId}": {
      "post": {
        "tags": [
          "transactions"
        ],
        "summary": "Create transactions (atomic)",
        "description": "Scopes [control.events:actors.management]\n\nThis API method ensures that every transaction is either explicitly committed or rolled back.\n",
        "operationId": "createTransactionAtomic",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/transactions/{accountId}/authorized": {
      "post": {
        "tags": [
          "transactions"
        ],
        "summary": "Authorize transaction (2-Step)",
        "description": "Scopes [control.events:actors.management]\n\nThis API supports two-step transactions, so you can first authorize, then wait to complete or cancel it later.\nAuthorizing a transaction places a hold on the account for the specified amount.\n\nWaiting for completion or cancellation can be limited with the `expiration` parameter for an authorized transaction.\nWhen the authorized transaction expires, the reversed transaction will be created automatically.\n\nSave transaction [...]",
        "operationId": "authTransaction2Step",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/transactions/{accountId}/completed": {
      "post": {
        "tags": [
          "transactions"
        ],
        "summary": "Complete transaction (2-Step)",
        "description": "Scopes [control.events:actors.management]\n\nYou can complete transaction that was previously authorized (use its ID).\nThis is the second half of the two-step transaction flow.\n\nYou cannot complete an authorized transaction that has been already canceled or expired.\n",
        "operationId": "completeTransaction2Step",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/transfers/{transferId}": {
      "get": {
        "tags": [
          "transfers"
        ],
        "summary": "Get transfer by id",
        "description": "Scopes [control.events:actors.readonly]",
        "operationId": "getTransferById",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.readonly"
            ]
          }
        ]
      }
    },
    "/transfers/filter/{accId}": {
      "post": {
        "tags": [
          "transfers"
        ],
        "summary": "Filter transfers",
        "description": "Scopes [control.events:actors.readonly]",
        "operationId": "transferFilter",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.readonly"
            ]
          }
        ]
      }
    },
    "/transfers/{accId}": {
      "post": {
        "tags": [
          "transfers"
        ],
        "summary": "Create transfer",
        "description": "Scopes [control.events:actors.readonly]",
        "operationId": "createTransfer",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.readonly"
            ]
          }
        ]
      }
    },
    "/transfers/{accId}/authorized": {
      "post": {
        "tags": [
          "transfers"
        ],
        "summary": "Create transfer holding",
        "description": "Scopes [control.events:actors.readonly]",
        "operationId": "createTransferHolding",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.readonly"
            ]
          }
        ]
      }
    },
    "/transactions/{accountId}/canceled": {
      "post": {
        "tags": [
          "transactions"
        ],
        "summary": "Cancel transaction (2-Step)",
        "description": "Scopes [control.events:actors.management]\n\nYou can cancel transaction that was previously authorized (use its ID).\n\nYou cannot cancel an authorized transaction that has been already completed or expired.\n",
        "operationId": "cancelTransaction2Step",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/account_names/{accId}": {
      "get": {
        "tags": [
          "account names"
        ],
        "summary": "Get account names",
        "description": "Scopes [control.events:actors.readonly]",
        "operationId": "getAccountNames",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.readonly"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "account names"
        ],
        "summary": "Create account name",
        "description": "Scopes [control.events:actors.management]",
        "operationId": "createAccountName",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/currencies/{accId}": {
      "get": {
        "tags": [
          "currencies"
        ],
        "summary": "Get currencies",
        "description": "Scopes [control.events:actors.readonly]",
        "operationId": "getCurrencies",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.readonly"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "currencies"
        ],
        "summary": "Create currency",
        "description": "Scopes [control.events:actors.management]",
        "operationId": "createCurrency",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/edge_types/{accId}": {
      "get": {
        "tags": [
          "link types"
        ],
        "summary": "Get link types list",
        "description": "Scopes [control.events:actors.readonly]\n\nLink type is an attribute of every link between actors.\nE.g., on the Economics layer - a link type with the name `calculatedTree` is used, on other layers - a hierarchical link (with the name `hierarchy`).\n\nThere is a set of specific link types used for links between actors in the accounts tree.\nFor every existing actor's account (unique pair of name and currency), there is a dedicated link type.<br/>\nSuch link type name is [...]",
        "operationId": "getEdgeTypes",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.readonly"
            ]
          }
        ]
      }
    },
    "/access_rules/{objType}/{objId}": {
      "get": {
        "tags": [
          "access rules"
        ],
        "summary": "Get access info",
        "description": "The scope depends on what object do you want to manage access to.\n\n| Object type | Scope |\n| ------- | --------|\n| formTemplate | [control.events:forms.readonly] |\n| actor | [control.events:actors.readonly] |\n",
        "operationId": "getAccessInfo",
        "security": [
          {
            "OAuth2": [
              "control.events:forms.readonly",
              "control.events:actors.readonly"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "access rules"
        ],
        "summary": "Manage access rules",
        "description": "The scope depends on what object do you want to manage access to.\n\n| Object type | Scope |\n| ------- | --------|\n| formTemplate | [control.events:forms.management] |\n| actor | [control.events:actors.management] |\n",
        "paths": {
          "/": null
        },
        "operationId": "manageAccessRules",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management",
              "control.events:forms.management"
            ]
          }
        ]
      }
    },
    "/users/anonymous/{actorId}/{userId}": {
      "put": {
        "tags": [
          "users"
        ],
        "summary": "Rename anonymous user",
        "description": "Scopes [control.events:users.management]",
        "operationId": "renameAnonymousUser",
        "security": [
          {
            "OAuth2": [
              "control.events:users.management"
            ]
          }
        ]
      }
    },
    "/realtime/interface/{accId}/{name}": {
      "post": {
        "tags": [
          "realtime"
        ],
        "summary": "Realtime proxy packets to interface",
        "description": "Scopes [control.events:workspaces.readonly]",
        "operationId": "realtimeInterface",
        "security": [
          {
            "OAuth2": [
              "control.events:workspaces.readonly"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "OAuth2": {
        "type": "oauth2",
        "description": "Control Events use the OAuth 2.0 protocol for authentication and authorization. Control Events supports common OAuth 2.0 scenarios such as those for web server, installed, and client-side applications.<br/><br/>\nIf you want to make requests on behalf of other control.events users, you can register an OAuth application and have them grant permissions to your app.",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://account.corezoid.com/oauth2/authorize",
            "tokenUrl": "https://account.corezoid.com/oauth2/token",
            "scopes": {
              "control.events:users.readonly": "View workspace users information",
              "control.events:workspaces.readonly": "View all your workspaces",
              "control.events:forms.readonly": "View forms",
              "control.events:forms.management": "Create, update, and delete forms",
              "control.events:actors.readonly": "View actors info",
              "control.events:actors.management": "Create, update, and delete actors",
              "control.events:attachments.readonly": "View attachments",
              "control.events:attachments.management": "Create, update, and delete attachments"
            }
          }
        }
      },
      "BearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "description": "You can generate an API <b>access_token</b> for your workspace on the <a href='https://doc.corezoid.com/docs/api-keys-1'>Account</a>  <b>(Account -> API Keys)</b>. <br/><br/> To use an API <b>access_token</b> to authenticate an API request, just replace <b>access_token</b> in the following API endpoints with the string key, and pass the Authorization header:<br/><br/> <b>Authorization: Bearer YOUR_ACCESS_TOKEN</b>"
      }
    }
  }
}