{
  "openapi": "3.0.1",
  "info": {
    "title": "Simulator.Company REST API",
    "description": "Simulator.Company Public REST API.\n\n# Authentication\n\n<!-- ReDoc-Inject: <security-definitions> -->",
    "x-logo": {
      "url": "https://sim.simulator.company/static/logo.svg",
      "padding": "24px",
      "altText": "Simulator.Company"
    },
    "contact": {
      "email": "support@simulator.company"
    },
    "version": "1.0"
  },
  "servers": [
    {
      "url": "https://mw-api.simulator.company/v/1.0"
    }
  ],
  "tags": [
    {
      "name": "reactions",
      "description": "Reactions API"
    },
    {
      "name": "upload",
      "description": "Upload API"
    },
    {
      "name": "download",
      "description": "Download API"
    },
    {
      "name": "attachments",
      "description": "Attachments API"
    },
    {
      "name": "forms",
      "description": "Forms API"
    },
    {
      "name": "meta graph",
      "description": "Meta graph API"
    },
    {
      "name": "layers",
      "description": "Layers API"
    },
    {
      "name": "actors",
      "description": "Actors API"
    },
    {
      "name": "links",
      "description": "Actors links API"
    },
    {
      "name": "link types",
      "description": "Link types API"
    },
    {
      "name": "accounts",
      "description": "Actors accounts API"
    },
    {
      "name": "transactions",
      "description": "Transactions API"
    },
    {
      "name": "transfers",
      "description": "Transfers API"
    },
    {
      "name": "account names",
      "description": "Accounts names API"
    },
    {
      "name": "currencies",
      "description": "Accounts currencies API"
    },
    {
      "name": "access rules",
      "description": "Access rules API"
    },
    {
      "name": "users",
      "description": "Users API"
    },
    {
      "name": "realtime",
      "description": "Realtime API"
    }
  ],
  "paths": {
    "/forms/templates/{accId}": {
      "get": {
        "tags": [
          "forms"
        ],
        "summary": "Get list of forms",
        "description": "Scopes [control.events:forms.readonly]",
        "operationId": "getForms",
        "security": [
          {
            "OAuth2": [
              "control.events:forms.readonly"
            ]
          }
        ]
      }
    },
    "/forms/templates/system/{accId}?formTypes=system": {
      "get": {
        "tags": [
          "forms"
        ],
        "summary": "Get list of system forms",
        "description": "This API is used to get system forms:\n* Graphs\n* Layers\n* Streams\n* Events\n* Widgets\n* Scripts\n* Locations\n* Tags\n* Reactions\n\nScopes [control.events:forms.readonly]\n",
        "operationId": "getSystemForms",
        "x-invisible": true,
        "security": [
          {
            "OAuth2": [
              "control.events:forms.readonly"
            ]
          }
        ]
      }
    },
    "/forms/{accId}/{isTemplate}": {
      "post": {
        "tags": [
          "forms"
        ],
        "summary": "Create form",
        "description": "Scopes [control.events:forms.management]",
        "operationId": "createForm",
        "security": [
          {
            "OAuth2": [
              "control.events:forms.management"
            ]
          }
        ]
      }
    },
    "/forms/status/{formId}": {
      "put": {
        "tags": [
          "forms"
        ],
        "summary": "Set form status",
        "description": "Scopes [control.events:forms.management]",
        "operationId": "setFormStatus",
        "security": [
          {
            "OAuth2": [
              "control.events:forms.management"
            ]
          }
        ]
      }
    },
    "/forms/ref/{ref}": {
      "get": {
        "tags": [
          "forms"
        ],
        "summary": "Get form by ref",
        "description": "Scopes [control.events:forms.readonly]",
        "operationId": "getFormByRef",
        "security": [
          {
            "OAuth2": [
              "control.events:forms.readonly"
            ]
          }
        ]
      }
    },
    "/forms/{formId}": {
      "get": {
        "tags": [
          "forms"
        ],
        "summary": "Get form by ID",
        "description": "Scopes [control.events:forms.readonly]",
        "operationId": "getForm",
        "security": [
          {
            "OAuth2": [
              "control.events:forms.readonly"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "forms"
        ],
        "summary": "Update form",
        "description": "Scopes [control.events:forms.management]",
        "operationId": "updateForm",
        "security": [
          {
            "OAuth2": [
              "control.events:forms.management"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "forms"
        ],
        "summary": "Remove form",
        "description": "Scopes [control.events:forms.management]",
        "operationId": "deleteForm",
        "security": [
          {
            "OAuth2": [
              "control.events:forms.management"
            ]
          }
        ]
      }
    },
    "/form_accounts/{formId}": {
      "post": {
        "tags": [
          "forms"
        ],
        "summary": "Add account-currency pair to form",
        "description": "Adds an account-currency pair to the specified form. Scopes [control.events:forms.management]",
        "operationId": "addFormAccount",
        "security": [
          {
            "OAuth2": [
              "control.events:forms.management"
            ]
          }
        ]
      }
    },
    "/forms/item_cache/{formId}/{itemId}": {
      "delete": {
        "tags": [
          "forms"
        ],
        "summary": "Clear cache for form item options",
        "description": "Helps to clear cache for form item options, where source type is 'api'.<br/><br/> Scopes [control.events:forms.management]",
        "operationId": "clearFromItemSourceCache",
        "security": [
          {
            "OAuth2": [
              "control.events:forms.management"
            ]
          }
        ]
      }
    },
    "/graph/linked_actors/{actorId}": {
      "get": {
        "tags": [
          "meta graph"
        ],
        "summary": "Get linked actors with links",
        "description": "Scopes [control.events:actors.readonly]",
        "operationId": "getLinkedActors",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.readonly"
            ]
          }
        ]
      }
    },
    "/graph/actor_links/{actorId}": {
      "get": {
        "tags": [
          "meta graph"
        ],
        "summary": "Get all actor links",
        "description": "Scopes [control.events:actors.readonly]",
        "operationId": "getActorLinks",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.readonly"
            ]
          }
        ]
      }
    },
    "/actors/exist_link": {
      "post": {
        "tags": [
          "meta graph"
        ],
        "summary": "Check if link exists",
        "description": "Scopes [control.events:actors.readonly]",
        "operationId": "existLink",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.readonly"
            ]
          }
        ]
      }
    },
    "/graph/{type}/{actorId}": {
      "get": {
        "tags": [
          "meta graph"
        ],
        "summary": "Get linked actors",
        "description": "Scopes [control.events:actors.readonly]",
        "operationId": "getLinked",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.readonly"
            ]
          }
        ]
      }
    },
    "/graph_layers/{layerId}": {
      "get": {
        "tags": [
          "layers"
        ],
        "summary": "Get layer",
        "description": "Scopes [control.events:actors.readonly]\n\nA layer is an actor created with system form [Layers](api.html#operation/getSystemForms).\nThis API retrieves all layer actor data together with it's nodes and links.\n",
        "operationId": "getLayer",
        "x-invisible": true,
        "security": [
          {
            "OAuth2": [
              "control.events:actors.readonly"
            ]
          }
        ]
      }
    },
    "/graph_layers/actors/{layerId}": {
      "post": {
        "tags": [
          "layers"
        ],
        "summary": "Manage layer elements",
        "description": "Scopes [control.events:actors.management]",
        "operationId": "manageLayer",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "layers"
        ],
        "summary": "Save layer nodes positions on layer",
        "description": "Scopes [control.events:actors.management]",
        "operationId": "layerActorsPosition",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/graph_layers/move/{sourceLayerId}/{targetLayerId}": {
      "post": {
        "tags": [
          "layers"
        ],
        "summary": "Move actors to another layer",
        "description": "Scopes [control.events:actors.management]",
        "operationId": "moveElements",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/graph_layers/clean/{layerId}": {
      "delete": {
        "tags": [
          "layers"
        ],
        "summary": "Clear the layer",
        "description": "Scopes [control.events:actors.management]",
        "operationId": "cleanLayer",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/graph_layers/exist/{layerId}": {
      "post": {
        "tags": [
          "layers"
        ],
        "summary": "Check element existence",
        "description": "Scopes [control.events:actors.readonly]\n\nThis method searches an element on the layer and returns a list of their layer-unique IDs.\n",
        "operationId": "exist",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/layer_actors_filters/search/{layerId}/{query}": {
      "get": {
        "tags": [
          "layers"
        ],
        "summary": "Search layer actors",
        "description": "Scopes [control.events:actors.readonly]",
        "operationId": "searchLayerActors",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/layer_actors_filters/{layerId}/{formId}": {
      "get": {
        "tags": [
          "layers"
        ],
        "summary": "Get layer actors by form ID",
        "description": "Scopes [control.events:actors.readonly]\n\nThis method returns all layer actors filtered by form ID.\n",
        "operationId": "getLayerActorsByFormId",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/layers_links/actor_global/{actorId}": {
      "get": {
        "tags": [
          "layers"
        ],
        "summary": "Get all graph layers with actor",
        "description": "Scopes [control.events:actors.readonly]\n\nThis method retrieves all layers where the actor is added.\n",
        "operationId": "actorGlobalLayers",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/actors/actor/{formId}": {
      "post": {
        "tags": [
          "actors"
        ],
        "summary": "Create actor",
        "description": "Scopes [control.events:actors.management]",
        "operationId": "createActor",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/actors/{actorId}": {
      "get": {
        "tags": [
          "actors"
        ],
        "summary": "Get actor by ID",
        "description": "Scopes [control.events:actors.readonly]",
        "operationId": "getActor",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.readonly"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "actors"
        ],
        "summary": "Remove actor by ID",
        "description": "Scopes [control.events:actors.management]",
        "operationId": "deleteActor",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/actors": {
      "delete": {
        "tags": [
          "actors"
        ],
        "summary": "Remove multiple actors and links",
        "description": "Scopes [control.events:actors.management]",
        "operationId": "deleteBulk",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/actors/actor/{formId}/{actorId}": {
      "put": {
        "tags": [
          "actors"
        ],
        "summary": "Update actor by ID",
        "description": "Scopes [control.events:actors.management]",
        "operationId": "updateActor",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/actors/ref/{formId}/{ref}": {
      "get": {
        "tags": [
          "actors"
        ],
        "summary": "Get actor by ref",
        "description": "Scopes [control.events:actors.readonly]",
        "operationId": "getActorByRef",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.readonly"
            ]
          }
        ]
      }
    },
    "/actors/system/{accId}/{objType}/{objId}": {
      "get": {
        "tags": [
          "actors"
        ],
        "summary": "Get actor by systemObjId",
        "description": "Scopes [control.events:actors.readonly]",
        "operationId": "getActorByObjId",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.readonly"
            ]
          }
        ]
      }
    },
    "/actors/ref/{{formId}}/{{ref}}": {
      "delete": {
        "tags": [
          "actors"
        ],
        "summary": "Remove actor by ref",
        "description": "Scopes [control.events:actors.management]",
        "operationId": "deleteActorByRef",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/actors/actor/ref/{formId}/{ref}": {
      "put": {
        "tags": [
          "actors"
        ],
        "summary": "Update actor by ref",
        "description": "Scopes [control.events:actors.management]",
        "operationId": "updateActorByRef",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/actors/status/{actorId}": {
      "put": {
        "tags": [
          "actors"
        ],
        "summary": "Set actor status",
        "description": "Scopes [control.events:actors.management]",
        "operationId": "setActorStatus",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/actors_filters/search/{accId}/{query}": {
      "get": {
        "tags": [
          "actors"
        ],
        "summary": "Search actors",
        "description": "Scopes [control.events:actors.readonly]",
        "operationId": "searchActors",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.readonly"
            ]
          }
        ]
      }
    },
    "/actors_filters/{formId}": {
      "get": {
        "tags": [
          "actors"
        ],
        "summary": "Filter actors by form",
        "description": "Scopes [control.events:actors.readonly]. Samples of params: Get only one actor and specify fields to return: \n  {\"from\": 0, \"to\": 1755540313, \"limit\":1, \"filter\":\"id,title\"} \n Get first 10 actors with all fields: \n  {\"from\": 0, \"to\": 1755540313, \"limit\":10}",
        "operationId": "filterActors",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.readonly"
            ]
          }
        ]
      }
    },
    "/actors/link/{accId}": {
      "post": {
        "tags": [
          "links"
        ],
        "summary": "Create link between actors",
        "description": "Scopes [control.events:actors.management]",
        "operationId": "createLink",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/actors/mass_links/{accId}": {
      "post": {
        "tags": [
          "links"
        ],
        "summary": "Create multiple links",
        "description": "Scopes [control.events:actors.management]",
        "operationId": "massLink",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/actors/link/{edgeId}": {
      "put": {
        "tags": [
          "links"
        ],
        "summary": "Update link",
        "description": "Scopes [control.events:actors.management]",
        "operationId": "updateLink",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "links"
        ],
        "summary": "Remove link",
        "description": "Scopes [control.events:actors.management]",
        "operationId": "deleteLink",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/actors/bulk/actors_link": {
      "delete": {
        "tags": [
          "links"
        ],
        "summary": "Mass remove links",
        "description": "Scopes [control.events:actors.management]",
        "operationId": "bulkDeleteLinks",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/account_names/{accId}": {
      "get": {
        "tags": [
          "account names"
        ],
        "summary": "Get account names",
        "description": "Scopes [control.events:actors.readonly]",
        "operationId": "getAccountNames",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.readonly"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "account names"
        ],
        "summary": "Create account name",
        "description": "Scopes [control.events:actors.management]",
        "operationId": "createAccountName",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/currencies/{accId}": {
      "get": {
        "tags": [
          "currencies"
        ],
        "summary": "Get currencies",
        "description": "Scopes [control.events:actors.readonly]",
        "operationId": "getCurrencies",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.readonly"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "currencies"
        ],
        "summary": "Create currency",
        "description": "Scopes [control.events:actors.management]",
        "operationId": "createCurrency",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management"
            ]
          }
        ]
      }
    },
    "/edge_types/{accId}": {
      "get": {
        "tags": [
          "link types"
        ],
        "summary": "Get link types list",
        "description": "Scopes [control.events:actors.readonly]\n\nLink type is an attribute of every link between actors.\nE.g., on the Economics layer - a link type with the name `calculatedTree` is used, on other layers - a hierarchical link (with the name `hierarchy`).\n\nThere is a set of specific link types used for links between actors in the accounts tree.\nFor every existing actor's account (unique pair of name and currency), there is a dedicated link type.<br/>\nSuch link type name is [...]",
        "operationId": "getEdgeTypes",
        "x-invisible": true,
        "security": [
          {
            "OAuth2": [
              "control.events:actors.readonly"
            ]
          }
        ]
      }
    },
    "/access_rules/{objType}/{objId}": {
      "get": {
        "tags": [
          "access rules"
        ],
        "summary": "Get access info",
        "description": "The scope depends on what object do you want to manage access to.\n\n| Object type | Scope |\n| ------- | --------|\n| formTemplate | [control.events:forms.readonly] |\n| actor | [control.events:actors.readonly] |\n",
        "operationId": "getAccessInfo",
        "security": [
          {
            "OAuth2": [
              "control.events:forms.readonly",
              "control.events:actors.readonly"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "access rules"
        ],
        "summary": "Manage access rules",
        "description": "The scope depends on what object do you want to manage access to.\n\n| Object type | Scope |\n| ------- | --------|\n| formTemplate | [control.events:forms.management] |\n| actor | [control.events:actors.management] |\n",
        "paths": {
          "/": null
        },
        "operationId": "manageAccessRules",
        "security": [
          {
            "OAuth2": [
              "control.events:actors.management",
              "control.events:forms.management"
            ]
          }
        ]
      }
    },
    "/users/anonymous/{actorId}/{userId}": {
      "put": {
        "tags": [
          "users"
        ],
        "summary": "Rename anonymous user",
        "description": "Scopes [control.events:users.management]",
        "operationId": "renameAnonymousUser",
        "security": [
          {
            "OAuth2": [
              "control.events:users.management"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "OAuth2": {
        "type": "oauth2",
        "description": "Control Events use the OAuth 2.0 protocol for authentication and authorization. Control Events supports common OAuth 2.0 scenarios such as those for web server, installed, and client-side applications.<br/><br/>\nIf you want to make requests on behalf of other control.events users, you can register an OAuth application and have them grant permissions to your app.",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://account.corezoid.com/oauth2/authorize",
            "tokenUrl": "https://account.corezoid.com/oauth2/token",
            "scopes": {
              "control.events:users.readonly": "View workspace users information",
              "control.events:workspaces.readonly": "View all your workspaces",
              "control.events:forms.readonly": "View forms",
              "control.events:forms.management": "Create, update, and delete forms",
              "control.events:actors.readonly": "View actors info",
              "control.events:actors.management": "Create, update, and delete actors",
              "control.events:attachments.readonly": "View attachments",
              "control.events:attachments.management": "Create, update, and delete attachments"
            }
          }
        }
      },
      "BearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "description": "You can generate an API <b>access_token</b> for your workspace on the <a href='https://doc.corezoid.com/docs/api-keys-1'>Account</a>  <b>(Account -> API Keys)</b>. <br/><br/> To use an API <b>access_token</b> to authenticate an API request, just replace <b>access_token</b> in the following API endpoints with the string key, and pass the Authorization header:<br/><br/> <b>Authorization: Bearer YOUR_ACCESS_TOKEN</b>"
      }
    }
  }
}